# Generated by Django 5.0 on 2023-12-17 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(default='', max_length=50)),
                ('contact_number', models.IntegerField(default='9800000000')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile-picture')),
                ('background_cover', models.ImageField(default='back-default.jpg', upload_to='profile-picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
